### ISSUE TITLE
Model Testing for EOS81EW

### ISSUE THREAD

**Issue by paulinebanye** [ersilia-os/eos81ew#2]
### Model Test
Hi @GemmaTuron 
### MODEL TEST FOR EOS81EW
I tested the model on my local environment and on the Ersilia CLI with the --repo_path option.

## Result
- [x] Model eos81ew fetched, served and ran successfully on the CLI.
- [X] Model was tested using a list of smiles and a single smile string
[eos81ew_fetch.log](https://github.com/ersilia-os/eos81ew/files/10840248/eos81ew_fetch.log)
[eos81ew_list_run.csv](https://github.com/ersilia-os/eos81ew/files/10840251/eos81ew_list_run.csv)
[eos81ew_run.csv](https://github.com/ersilia-os/eos81ew/files/10840253/eos81ew_run.csv)

**Comment by GemmaTuron** [comment]
Hi @Femme-js and @DhanshreeA the model is ready for testing!

**Comment by AhmedYusuff** [comment]
Hi @GemmaTuron.

I ran the model several times on my Local environment, which is Ubuntu 22.04.

While fetching the model i got  a `KeyError: 'Input'` error message.

I have attached the log file below

[my.log](https://github.com/ersilia-os/eos81ew/files/10921342/my.log)

**Comment by GemmaTuron** [comment]
Hi @AhmedYusuff 

Thanks for testing. While the final output of the log file is indeed `KeyError: Input,` you need to look through the log file to locate the real source of the error. In your case, that seems to be _socket.timeout: The read operation timed out_ which points to an internet connection issue? try to do some googling / reading on that!
Fyi and @pauline-banye , I've been able to successfully fetch and run the model in my Ubuntu 20.04

**Comment by AhmedYusuff** [comment]
Hello @GemmaTuron, I've been able to resolve the `KeyError: Input ` error.

But I seem to have encountered another error `Model API eos81ew:run did not produce an outputLoading PAMPA graph convolutional neural network model`.

My log file is below
[new.log](https://github.com/ersilia-os/eos81ew/files/10926724/new.log)

**Comment by paulinebanye** [comment]
> Hello @GemmaTuron, I've been able to resolve the `KeyError: Input ` error.
> 
> But I seem to have encountered another error `Model API eos81ew:run did not produce an outputLoading PAMPA graph convolutional neural network model`.
> 
> My log file is below [new.log](https://github.com/ersilia-os/eos81ew/files/10926724/new.log)

Hi @AhmedYusuff, I tested the model and it fetched successfully.
[eos81ew_fetch.log](https://github.com/ersilia-os/eos81ew/files/10926981/eos81ew_fetch.log). Could you try running the fetch command again?

*Probably unrelated but its best you delete models that are not in use. run `ersilia delete <name-of-model>`

**Comment by AhmedYusuff** [comment]
Hi @pauline-banye, Looking through the error log, it seems to be having trouble calculating the Metadata on my end here.

Looking through the model repo 

https://github.com/ersilia-os/eos81ew 

The slug or model identifier  I'm getting while fetching `Pampa5` seems to be different from what you have `parallel-artificial-membrane-permeability-assay-5`

Could that be a problem?

**Comment by paulinebanye** [comment]
> Hi @pauline-banye, Looking through the error log, it seems to be having trouble calculating the Metadata on my end here.
> 
> Looking through the model repo 
> 
> https://github.com/ersilia-os/eos81ew 
> 
> The slug or model identifier  I'm getting while fetching `Pampa5` seems to be different from what you have `parallel-artificial-membrane-permeability-assay-5`
> 
> Could that be a problem?
> 

It could be actually. Let me make a PR to change this, then we can test the model again.

**Comment by GemmaTuron** [comment]
Hi @pauline-banye 

I am working on reformatting the metadata for all the NCATS models.
Please do not edit it as we are changing the airtable - metadata updates to fix a bug

**Comment by paulinebanye** [comment]
@AhmedYusuff I've made the PR, you can test again once @GemmaTuron merges it.

**Comment by pauline-banye** [comment]
Made the PR, you can test again once @GemmaTuron merges it.

**Comment by GemmaTuron** [comment]
Hi @AhmedYusuff 

Your error is at loading the model checkpoints. 
`PermissionError: [Errno 13] Permission denied: '../../checkpoints'`

Can you try cloning the model in your system, and then running the fetch command but adding the flag at the end `--repo-path <path_to_cloned_repo>`

@pauline-banye can provide more guidance on how to do this.
In any case I've updated the metadata files as well

Thanks!

**Comment by paulinebanye** [comment]
> Hi @pauline-banye 
> 
> I am working on reformatting the metadata for all the NCATS models.
> Please do not edit it as we are changing the airtable - metadata updates to fix a bug

Sure @GemmaTuron, I understand.

**Comment by AhmedYusuff** [comment]
Hello @pauline-banye , Should I change the directory to the Model or I should just specify the path in `--repo_path` ?

**Comment by GemmaTuron** [comment]
> Hello @pauline-banye , Should I change the directory to the Model or I should just specify the path in `--repo_path` ?

This might help @AhmedYusuff: [docs](https://ersilia.gitbook.io/ersilia-book/ersilia-model-hub/contribute-models/example-of-the-model-incorporation-workflow#8.-run-the-model-within-the-ersilia-cli.)

**Comment by AhmedYusuff** [comment]
Many thanks, @GemmaTuron.

From what I can see, it seems that I don't have the necessary permission to open some files. That's why I keep getting this error message.

@pauline-banye, Can you please make the  "gccn_model.pt"  file in the Checkpoints directory Executable for other users and groups,  I did that with the repo clone on my system, but I'm still getting the same error.

**Comment by AhmedYusuff** [comment]
Hi @GemmaTuron and @pauline-banye . This problem seems related to Ubuntu 22.04.

I tested the Model on Google Colab and it was successful. I was able to Fetch, serve and Predict. Attach is the link.

https://colab.research.google.com/drive/177w3Vfsby2sjMn8bzo821rheb9hL_U7V?usp=sharing

**Comment by paulinebanye** [comment]
> Many thanks, @GemmaTuron.
> 
> From what I can see, it seems that I don't have the necessary permission to open some files. That's why I keep getting this error message.
> 
> @pauline-banye, Can you please make the  "gccn_model.pt"  file in the Checkpoints directory Executable for other users and groups,  I did that with the repo clone on my system, but I'm still getting the same error.

Hi @AhmedYusuff, the gc n_model.pt is the model data itself. Could you clarify why it needs to be executable?

**Comment by paulinebanye** [comment]
> Hello @pauline-banye , Should I change the directory to the Model or I should just specify the path in `--repo_path` ?

Hi @AhmedYusuff could you share the command you specified to run the fetch command with the repo path flag?

**Comment by AhmedYusuff** [comment]
This is the command 

> > Hello @pauline-banye , Should I change the directory to the Model or I should just specify the path in `--repo_path` ?
> 
> Hi @AhmedYusuff could you share the command you specified to run the fetch command with the repo path flag?

I used this command. `ersilia -v fetch eos81ew --repo_path /home/control/eos81ew/`

**Comment by AhmedYusuff** [comment]
> > Many thanks, @GemmaTuron.
> > From what I can see, it seems that I don't have the necessary permission to open some files. That's why I keep getting this error message.
> > @pauline-banye, Can you please make the  "gccn_model.pt"  file in the Checkpoints directory Executable for other users and groups,  I did that with the repo clone on my system, but I'm still getting the same error.
> 
> Hi @AhmedYusuff, the gc n_model.pt is the model data itself. Could you clarify why it needs to be executable?

@pauline-banye , The permission denied error messages pointed me to `../../checkpoints`

**Comment by AhmedYusuff** [comment]
Hello @pauline-banye , @GemmaTuron.

The issue has been resolved and Model Fetched and tested Successfully on Ubuntu 22.04.

The Model was trying to create a directory, But the User had insufficient permission, So I had to grant the user Privileges.

This is the fetch log.
[eos81ewfetch.log](https://github.com/ersilia-os/eos81ew/files/10940077/eos81ewfetch.log)

The Model was tested with a simple smile string.
[eos81ewtest.csv](https://github.com/ersilia-os/eos81ew/files/10940123/eos81ewtest.csv)

**Comment by paulinebanye** [comment]
> Hello @pauline-banye , @GemmaTuron.
> 
> The issue has been resolved and Model Fetched and tested Successfully.
> 
> The Model was trying to create a directory, But the User had insufficient permission, So I had to grant the user Privileges.
> 
> This is the fetch log.
> [eos81ewfetch.log](https://github.com/ersilia-os/eos81ew/files/10940077/eos81ewfetch.log)
> 
> The Model was tested with a simple smile string.
> [eos81ewtest.csv](https://github.com/ersilia-os/eos81ew/files/10940123/eos81ewtest.csv)
> 
>  

That's good to hear @AhmedYusuff 😊. Good job debugging 👍🏻.

**Comment by AhmedYusuff** [comment]
> > Hello @pauline-banye , @GemmaTuron.
> > The issue has been resolved and Model Fetched and tested Successfully.
> > The Model was trying to create a directory, But the User had insufficient permission, So I had to grant the user Privileges.
> > This is the fetch log.
> > [eos81ewfetch.log](https://github.com/ersilia-os/eos81ew/files/10940077/eos81ewfetch.log)
> > The Model was tested with a simple smile string.
> > [eos81ewtest.csv](https://github.com/ersilia-os/eos81ew/files/10940123/eos81ewtest.csv)
> 
> That's good to hear @AhmedYusuff 😊. Good job debugging 👍🏻.

Many thanks @pauline-banye . I'm happy to be of  help

**Comment by samuelmaina** [comment]
Used the 2 files(run and the list_run) provided by @pauline-banye . The model run successfully and provided the following out put.
[run_output.csv](https://github.com/ersilia-os/eos81ew/files/10953609/run_output.csv)  and 
[list_run_output.csv](https://github.com/ersilia-os/eos81ew/files/10953611/list_run_output.csv)

**Comment by GemmaTuron** [comment]
Perfect,

Thanks @AhmedYusuff and @samuelmaina for the work!
I'll mark this issue as completed and the model as functional in our database 🎉
